In [ ]:
!pip install pycaret

     |████████████████████████████████| 288 kB 5.0 MB/s 
     |████████████████████████████████| 1.7 MB 32.8 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 261 kB 19.9 MB/s 
     |████████████████████████████████| 56 kB 3.1 MB/s 
     |████████████████████████████████| 1.3 MB 16.9 MB/s 
     |████████████████████████████████| 86 kB 3.5 MB/s 
     |████████████████████████████████| 15.5 MB 35.0 MB/s 
     |████████████████████████████████| 6.8 MB 42.2 MB/s 
     |████████████████████████████████| 113 kB 46.8 MB/s 
     |████████████████████████████████| 2.0 MB 34.5 MB/s 
     |████████████████████████████████| 167 kB 55.5 MB/s 
     |████████████████████████████████| 675 kB 25.7 MB/s 
     |████████████████████████████████| 303 kB 43.9 MB/s 
     |████████████████████████████████| 62 kB 694 kB/s 
     |███████████████████

In [ ]:
!pip install --upgrade pycaret

In [ ]:
from pycaret.utils import enable_colab
enable_colab()

Colab mode enabled.


In [ ]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

dataset = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/telemonitoring/parkinsons_updrs.data',names=["subject#","age","sex","test_time","motor_UPDRS","total_UPDRS","Jitter(%)","Jitter(Abs)","Jitter:RAP","Jitter:PPQ5","Jitter:DDP","Shimmer","Shimmer(dB)","Shimmer:APQ3","Shimmer:APQ5","Shimmer:APQ11","Shimmer:DDA","NHR","HNR","RPDE","DFA","PPE"],header=None) 

dataset = dataset.drop(columns=['motor_UPDRS'])
dataset = dataset.drop([0])
dataset.head()

subject# age sex test_time  ...     HNR     RPDE      DFA      PPE
1        1  72   0    5.6431  ...   21.64  0.41888  0.54842  0.16006
2        1  72   0    12.666  ...  27.183  0.43493  0.56477   0.1081
3        1  72   0    19.681  ...  23.047  0.46222  0.54405  0.21014
4        1  72   0    25.647  ...  24.445   0.4873  0.57794  0.33277
5        1  72   0    33.642  ...  26.126  0.47188  0.56122  0.19361

[5 rows x 21 columns]

In [ ]:
dataset = dataset.drop(columns=['subject#'])
dataset.shape

(5875, 20)

In [ ]:
data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (5288, 20)
Unseen Data For Predictions: (587, 20)


In [ ]:
from pycaret.regression import *
exp_reg101 = setup(data = data, target = 'total_UPDRS', numeric_features=["test_time","sex","Jitter(%)","Jitter(Abs)","Jitter:RAP","Jitter:PPQ5","Jitter:DDP","Shimmer","Shimmer(dB)","Shimmer:APQ3","Shimmer:APQ5","Shimmer:APQ11","Shimmer:DDA","NHR","HNR","RPDE","DFA","PPE"], session_id=123) 

Description             Value
0                               session_id               123
1                                   Target       total_UPDRS
2                            Original Data        (5288, 20)
3                           Missing Values             False
4                         Numeric Features                19
5                     Categorical Features                 0
6                         Ordinal Features             False
7                High Cardinality Features             False
8                  High Cardinality Method              None
9                    Transformed Train Set        (3701, 17)
10                    Transformed Test Set        (1587, 17)
11                      Shuffle Train-Test              True
12                     Stratify Train-Test             False
13                          Fold Generator             KFold
14                             Fold Number                10
15                                CPU Jobs                -1
16                                 Use GPU             False
17                          Log Experiment             False
18                         Experiment Name  reg-default-name
19                                     USI              a668
20                         Imputation Type            simple
21          Iterative Imputation Iteration              None
22                         Numeric Imputer              mean
23      Iterative Imputation Numeric Model              None
24                     Categorical Imputer          constant
25  Iterative Imputation Categorical Model              None
26           Unknown Categoricals Handling    least_frequent
27                               Normalize             False
28                        Normalize Method              None
29                          Transformation             False
30                   Transformation Method              None
31                                     PCA             False
32                              PCA Method              None
33                          PCA Components              None
34                     Ignore Low Variance             False
35                     Combine Rare Levels             False
36                    Rare Level Threshold              None
37                         Numeric Binning             False
38                         Remove Outliers             False
39                      Outliers Threshold              None
40                Remove Multicollinearity             False
41             Multicollinearity Threshold              None
42             Remove Perfect Collinearity              True
43                              Clustering             False
44                    Clustering Iteration              None
45                     Polynomial Features             False
46                       Polynomial Degree              None
47                    Trignometry Features             False
48                    Polynomial Threshold              None
49                          Group Features             False
50                       Feature Selection             False
51                Feature Selection Method           classic
52            Features Selection Threshold              None
53                     Feature Interaction             False
54                           Feature Ratio             False
55                   Interaction Threshold              None
56                        Transform Target             False
57                 Transform Target Method           box-cox

In [ ]:
best = compare_models(exclude = ['ransac'])

Model      MAE       MSE     RMSE      R2  \
et            Extra Trees Regressor   1.0640    3.2483   1.7941  0.9717   
rf          Random Forest Regressor   1.0280    3.7619   1.9281  0.9672   
dt          Decision Tree Regressor   0.8361    7.9047   2.7678  0.9316   
gbr     Gradient Boosting Regressor   3.8696   24.2363   4.9194  0.7891   
ada              AdaBoost Regressor   7.1875   68.1035   8.2507  0.4076   
lr                Linear Regression   8.1273   96.1421   9.8034  0.1641   
lar          Least Angle Regression   8.1273   96.1423   9.8034  0.1641   
br                   Bayesian Ridge   8.1426   96.7777   9.8357  0.1586   
ridge              Ridge Regression   8.1475   97.1510   9.8546  0.1554   
huber               Huber Regressor   8.1232  100.1713  10.0045  0.1295   
en                      Elastic Net   8.4371  102.4321  10.1191  0.1095   
lasso              Lasso Regression   8.4341  102.4703  10.1210  0.1092   
omp     Orthogonal Matching Pursuit   8.5052  104.8492  10.2374  0.0886   
llar   Lasso Least Angle Regression   8.6974  115.5524  10.7473 -0.0043   
dummy               Dummy Regressor   8.6974  115.5524  10.7473 -0.0043   
par    Passive Aggressive Regressor  13.6979  282.7747  16.4552 -1.4742   

       RMSLE    MAPE  TT (Sec)  
et       0.0  0.0530     1.462  
rf       0.0  0.0496     3.504  
dt       0.0  0.0405     0.543  
gbr      0.0  0.1655     1.060  
ada      0.0  0.3151     0.483  
lr       0.0  0.3531     0.030  
lar      0.0  0.3531     0.031  
br       0.0  0.3539     0.047  
ridge    0.0  0.3548     0.031  
huber    0.0  0.3442     0.202  
en       0.0  0.3722     0.029  
lasso    0.0  0.3725     0.032  
omp      0.0  0.3804     0.030  
llar     0.0  0.4006     0.025  
dummy    0.0  0.4006     0.014  
par      0.0  0.5547     0.038

In [ ]:
#Extra Trees Regressor
et = create_model('et')

MAE     MSE    RMSE      R2  RMSLE    MAPE
0     1.0974  3.7115  1.9265  0.9673   -0.0  0.0618
1     1.0076  2.9556  1.7192  0.9730   -0.0  0.0476
2     1.0538  3.2840  1.8122  0.9713   -0.0  0.0568
3     1.0016  2.9115  1.7063  0.9750   -0.0  0.0520
4     0.9408  2.1169  1.4550  0.9830   -0.0  0.0432
5     1.0509  3.4152  1.8480  0.9701   -0.0  0.0525
6     0.9564  2.7129  1.6471  0.9763   -0.0  0.0487
7     1.0595  4.4544  2.1105  0.9610   -0.0  0.0488
8     1.0028  2.7685  1.6639  0.9769   -0.0  0.0483
9     0.9660  2.4440  1.5633  0.9777   -0.0  0.0483
Mean  1.0137  3.0774  1.7452  0.9732    0.0  0.0508
SD    0.0483  0.6364  0.1781  0.0058    0.0  0.0050

In [ ]:
print(et)

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=123, verbose=0, warm_start=False)


In [ ]:
#Random Forest Regressor
rf = create_model('rf')

MAE     MSE    RMSE      R2  RMSLE    MAPE
0     1.1706  4.6588  2.1584  0.9590   -0.0  0.0670
1     0.8825  2.4865  1.5769  0.9773   -0.0  0.0407
2     1.0640  4.0786  2.0196  0.9643   -0.0  0.0553
3     1.0729  3.5746  1.8907  0.9693   -0.0  0.0528
4     1.0046  3.0014  1.7325  0.9759   -0.0  0.0460
5     1.0511  4.4482  2.1091  0.9610   -0.0  0.0482
6     0.9766  4.0838  2.0208  0.9643   -0.0  0.0462
7     1.0296  5.1600  2.2716  0.9548   -0.0  0.0440
8     1.0112  2.8968  1.7020  0.9758   -0.0  0.0438
9     1.0399  3.3780  1.8379  0.9692   -0.0  0.0539
Mean  1.0303  3.7767  1.9319  0.9671    0.0  0.0498
SD    0.0699  0.8104  0.2104  0.0073    0.0  0.0073

In [ ]:
print (rf)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=123, verbose=0, warm_start=False)


In [ ]:
#Decision Tree Regressor
dt = create_model('dt')

MAE      MSE    RMSE      R2  RMSLE    MAPE
0     0.6967   7.0883  2.6624  0.9376   -0.0  0.0370
1     0.6624   4.5154  2.1250  0.9588   -0.0  0.0330
2     1.1250  11.4066  3.3774  0.9001   -0.0  0.0592
3     0.7890   5.9268  2.4345  0.9491   -0.0  0.0365
4     0.9726   9.8672  3.1412  0.9207   -0.0  0.0464
5     0.7533   6.2302  2.4960  0.9454   -0.0  0.0334
6     0.5054   4.0083  2.0021  0.9650   -0.0  0.0310
7     0.9360  11.5149  3.3934  0.8992   -0.0  0.0449
8     1.1654  11.2075  3.3478  0.9065   -0.0  0.0451
9     0.7552   7.2821  2.6985  0.9335   -0.0  0.0389
Mean  0.8361   7.9047  2.7678  0.9316    0.0  0.0405
SD    0.1988   2.7294  0.4939  0.0227    0.0  0.0081

In [ ]:
print (dt)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=123, splitter='best')


In [ ]:
tuned_et = tune_model(et)

MAE      MSE    RMSE      R2  RMSLE    MAPE
0     3.8041  25.4554  5.0453  0.7758   -0.0  0.1954
1     3.4390  19.9809  4.4700  0.8175   -0.0  0.1562
2     3.5458  21.6623  4.6543  0.8104   -0.0  0.1856
3     3.4653  20.6302  4.5421  0.8227   -0.0  0.1687
4     3.4798  20.2539  4.5004  0.8373   -0.0  0.1475
5     3.6314  21.3271  4.6181  0.8130   -0.0  0.1667
6     3.6699  22.5536  4.7491  0.8031   -0.0  0.1748
7     3.7129  23.1748  4.8140  0.7971   -0.0  0.1542
8     3.5020  19.8540  4.4558  0.8344   -0.0  0.1501
9     3.3759  18.5302  4.3047  0.8309   -0.0  0.1529
Mean  3.5626  21.3423  4.6154  0.8142    0.0  0.1652
SD    0.1294   1.8845  0.2014  0.0179    0.0  0.0153

In [ ]:
print(tuned_et)

ExtraTreesRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse', max_depth=9,
                    max_features=1.0, max_leaf_nodes=None, max_samples=None,
                    min_impurity_decrease=0.1, min_impurity_split=None,
                    min_samples_leaf=4, min_samples_split=7,
                    min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                    oob_score=False, random_state=123, verbose=0,
                    warm_start=False)


In [ ]:
tuned_rf = tune_model(rf)

MAE      MSE    RMSE      R2  RMSLE    MAPE
0     2.3715  11.3009  3.3617  0.9005   -0.0  0.1220
1     2.0974   7.9742  2.8239  0.9272   -0.0  0.0932
2     2.3290  10.1738  3.1896  0.9109   -0.0  0.1141
3     2.2005   9.1098  3.0182  0.9217   -0.0  0.1038
4     2.1624   8.8073  2.9677  0.9293   -0.0  0.0921
5     2.1655   9.6984  3.1142  0.9150   -0.0  0.0932
6     2.2558  10.3147  3.2116  0.9099   -0.0  0.1032
7     2.2404  10.9035  3.3020  0.9046   -0.0  0.0904
8     2.2358   8.9631  2.9938  0.9253   -0.0  0.0933
9     2.0445   8.0222  2.8323  0.9268   -0.0  0.0950
Mean  2.2103   9.5268  3.0815  0.9171    0.0  0.1000
SD    0.0940   1.0861  0.1761  0.0098    0.0  0.0101

In [ ]:
print(tuned_rf)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=9, max_features=1.0, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.1,
                      min_impurity_split=None, min_samples_leaf=4,
                      min_samples_split=7, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=123, verbose=0, warm_start=False)


In [ ]:
tuned_dt = tune_model(dt)

MAE      MSE    RMSE      R2  RMSLE    MAPE
0     1.5729  12.0919  3.4773  0.8935   -0.0  0.0818
1     1.4583   7.5701  2.7514  0.9308   -0.0  0.0630
2     1.4862   9.9563  3.1554  0.9128   -0.0  0.0697
3     1.3489   7.6716  2.7698  0.9341   -0.0  0.0630
4     1.4550  10.5712  3.2513  0.9151   -0.0  0.0670
5     1.2178   6.7036  2.5891  0.9412   -0.0  0.0493
6     1.1608   6.9160  2.6298  0.9396   -0.0  0.0546
7     1.2961  11.8079  3.4363  0.8966   -0.0  0.0586
8     1.7748  13.2342  3.6379  0.8896   -0.0  0.0703
9     1.1797   7.7748  2.7883  0.9291   -0.0  0.0559
Mean  1.3951   9.4298  3.0487  0.9183    0.0  0.0633
SD    0.1834   2.2767  0.3680  0.0186    0.0  0.0089

In [ ]:
print(tuned_dt)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='friedman_mse', max_depth=10,
                      max_features=1.0, max_leaf_nodes=None,
                      min_impurity_decrease=0.01, min_impurity_split=None,
                      min_samples_leaf=2, min_samples_split=9,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=123, splitter='best')


Moving forward with ET because it has the lowest R2

In [ ]:
evaluate_model(tuned_et)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [ ]:
predict_model(tuned_et);

Model     MAE      MSE    RMSE      R2  RMSLE    MAPE
0  Extra Trees Regressor  3.5544  21.0296  4.5858  0.8102      0  0.1639

R2 of the tuned et is 0.7758, and the R2 of the test/hold-out set is 0.8102.  A slight difference, may indicate a bit of overfitting.

In [ ]:
final_et = finalize_model(tuned_et)

In [ ]:
print(final_et)

ExtraTreesRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse', max_depth=9,
                    max_features=1.0, max_leaf_nodes=None, max_samples=None,
                    min_impurity_decrease=0.1, min_impurity_split=None,
                    min_samples_leaf=4, min_samples_split=7,
                    min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                    oob_score=False, random_state=123, verbose=0,
                    warm_start=False)


In [ ]:
predict_model(final_et)

Model     MAE      MSE    RMSE    R2  RMSLE    MAPE
0  Extra Trees Regressor  3.3403  18.8327  4.3397  0.83      0  0.1551

age  sex   test_time  Jitter(%)  ...      DFA      PPE  total_UPDRS      Label
0     66.0  1.0   72.412003    0.00662  ...  0.58131  0.29215       30.148  31.435751
1     55.0  0.0  117.779999    0.00506  ...  0.67158  0.18952       26.663  24.712023
2     65.0  0.0  159.429993    0.00346  ...  0.71290  0.17206       22.644  20.088121
3     58.0  0.0   59.354000    0.01109  ...  0.70848  0.28292           19  21.191671
4     61.0  0.0  149.839996    0.00297  ...  0.56518  0.12621       32.988  30.240151
...    ...  ...         ...        ...  ...      ...      ...          ...        ...
1582  55.0  0.0  183.820007    0.00983  ...  0.73418  0.32685       26.103  25.093455
1583  71.0  0.0   48.886002    0.00521  ...  0.72784  0.21694       54.556  48.518189
1584  63.0  0.0  131.339996    0.00442  ...  0.62377  0.14132       42.689  34.670856
1585  75.0  0.0   98.410004    0.00389  ...  0.63549  0.17484       42.232  39.078722
1586  85.0  1.0  138.470001    0.00487  ...  0.60658  0.15182        24.87  26.423298

[1587 rows x 19 columns]

R2 increased to 0.83 because the final_et variable is trained on the complete dataset. We need to predict on the unseen dataset.

In [ ]:
unseen_predictions = predict_model(final_et, data=data_unseen)
unseen_predictions.head()

age sex test_time total_UPDRS  ...     RPDE      DFA      PPE      Label
0  72   0    40.652       36.87  ...  0.53949  0.57243    0.195  33.273191
1  72   0     54.64      37.857  ...  0.47712  0.54234  0.23844  35.474805
2  72   0    82.653      39.834  ...  0.46686  0.57984   0.1939  34.076504
3  72   0    96.633      41.034  ...  0.61348  0.60661  0.15881  34.130583
4  72   0    131.64      44.146  ...  0.52714   0.5922  0.18211  30.799409

[5 rows x 21 columns]

In [ ]:
from pycaret.utils import check_metric
check_metric(unseen_predictions.total_UPDRS, unseen_predictions.Label, 'R2')

0.8288

Save the model

In [ ]:
save_model(final_et,'Final Extra Trees Model 14Dec2021')

Transformation Pipeline and Model Successfully Saved


(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=['test_time', 'sex',
                                                           'Jitter(%)',
                                                           'Jitter(Abs)',
                                                           'Jitter:RAP',
                                                           'Jitter:PPQ5',
                                                           'Jitter:DDP',
                                                           'Shimmer',
                                                           'Shimmer(dB)',
                                                           'Shimmer:APQ3',
                                                           'Shi

In [ ]:
saved_final_dt = load_model('Final Extra Trees Model 14Dec2021')

Transformation Pipeline and Model Successfully Loaded


In [ ]:
new_prediction = predict_model(saved_final_dt, data=data_unseen)

In [ ]:
new_prediction.head()

age sex test_time total_UPDRS  ...     RPDE      DFA      PPE      Label
0  72   0    40.652       36.87  ...  0.53949  0.57243    0.195  33.273191
1  72   0     54.64      37.857  ...  0.47712  0.54234  0.23844  35.474805
2  72   0    82.653      39.834  ...  0.46686  0.57984   0.1939  34.076504
3  72   0    96.633      41.034  ...  0.61348  0.60661  0.15881  34.130583
4  72   0    131.64      44.146  ...  0.52714   0.5922  0.18211  30.799409

[5 rows x 21 columns]

In [ ]:
from pycaret.utils import check_metric
check_metric(new_prediction.total_UPDRS, new_prediction.Label, 'R2')

0.8288